// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PlayerBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"player-bar\" class=\"player-bar inactive bg-dark text-white\" role=\"region\" aria-label=\"Now playing\"><div class=\"container py-3\"><div class=\"row align-items-center gy-3\"><div class=\"col-12 col-lg-4\"><div class=\"player-meta\"><div class=\"player-meta__title h6 mb-1\" id=\"player-track-title\">No track selected</div><div class=\"player-meta__details small\" id=\"player-track-meta\">Select a track to start playback.</div></div></div><div class=\"col-auto\"><div class=\"player-controls d-flex gap-2\"><button type=\"button\" class=\"btn btn-primary\" id=\"player-toggle\" aria-label=\"Play\" disabled><span aria-hidden=\"true\">Play</span></button> <button type=\"button\" class=\"btn btn-outline-light\" id=\"player-stop\" aria-label=\"Stop\" disabled><span aria-hidden=\"true\">Stop</span></button></div></div><div class=\"col-12 col-lg\"><div class=\"player-timeline d-flex flex-column gap-1\"><input type=\"range\" class=\"form-range\" id=\"player-progress\" min=\"0\" value=\"0\" step=\"0.1\" aria-label=\"Playback position\" disabled><div class=\"player-time small\" id=\"player-time\">--:-- / --:--</div></div></div><div class=\"col-auto\"><div class=\"player-volume d-flex align-items-center gap-2\"><label class=\"small mb-0\" for=\"player-volume-slider\">Vol</label> <input type=\"range\" class=\"form-range player-volume__slider\" id=\"player-volume-slider\" min=\"0\" max=\"100\" value=\"80\" aria-label=\"Volume\"></div></div></div></div><audio id=\"player-audio\" preload=\"none\" aria-hidden=\"true\"></audio></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
